# Generated by Django 3.0.7 on 2020-06-24 12:05

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200624_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
