# Generated by Django 3.0.7 on 2020-06-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200624_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='tz',
        ),
    ]
