# Generated by Django 3.0.7 on 2020-06-24 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200624_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='account.Member'),
        ),
    ]
