# Generated by Django 3.0.7 on 2020-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200624_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.CharField(max_length=12),
        ),
    ]
